apiVersion: apps/v1
kind: Deployment
metadata:
  name: k6-test-api
spec:
  template:
    spec:
      containers:
      - name: k6-test-api
        imagePullPolicy: Always
        image: loadimpact/test-api.k6.io:master-102
      imagePullSecrets:
      - name: dockerhub
