# Generated by Django 2.2.2 on 2019-07-05 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190628_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crocodile',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Crocs without an owner are considered public', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
