name: CI to Docker Hub
on:
  release:
    types:
      - published

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.K6_DOCKERHUB_USERNAME }}
          password: ${{ secrets.K6_DOCKERHUB_TOKEN }}      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./k8s/Dockerfile
          push: true
          tags: grafana/test-api.k6.io:latest,grafana/test-api.k6.io:${{ github.event.release.tag_name }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}